name: protirokkha
description: "Protirokkha - Community Safety Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Google Maps
  google_maps_flutter: ^2.9.0
  
  # State Management & Navigation
  go_router: ^14.6.2
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Add assets if needed
  # assets:
  #   - assets/images/
